# Workflow for using the makefile to create containers and run tests
name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-centos-v11_1_1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the project
      uses: actions/checkout@v3
    - name: build
      run: make VERTICA_VERSION=11.1.1 OSTAG=centos
    - name: test
      run: make VERTICA_VERSION=11.1.1 OSTAG=centos test
  test-ubuntu-v12_0_3:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the project
      uses: actions/checkout@v3
    - name: build
      run: make VERTICA_VERSION=12.0.3 OSTAG=ubuntu
    - name: test
      run: make VERTICA_VERSION=12.0.3 OSTAG=ubuntu test
