# Workflow for using the makefile to create containers and run tests
name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-centos-v11_1_1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the project
      uses: actions/checkout@v3
    - name: build another version using docker
      run: make VERTICA_VERSION=11.1.1 OSTAG=centos
    - name: Upload the shared object
      uses: actions/upload-artifact@v3
      with:
        name: ldblink-shared-object
        path: ldblink.so.centos-v11.1.1
  test:
    runs-on: ubuntu-latest
    needs: build-centos-v11_1_1
    steps:
    - name: Checkout the project
      uses: actions/checkout@v3
    - name: Download the shared object
      uses: actions/download-artifact@v2
      with:
        name: ldblink-shared-object
        path: ldblink.so.centos-v11.1.1
    - name: link ldblink.so
      run: ln -snf ldblink.so.centos-v11.1.1 ldblink.so
    - name: test
      run: make test
